### ISSUE TITLE
Smooth camera causes jitter when player size changes

### ISSUE THREAD

**Issue by machiecodes** [tma02/calico#6]
Enabling the "Smooth Camera" optimization causes the camera to jitter up and down very fast when drinking sodas that change your size, here is my mod list:

![image](https://github.com/user-attachments/assets/73f3e3a5-7da9-4b48-a3b4-71dd39fd27ae)

**Comment by tma02** [comment]
Thanks for the issue, I'll get a release out to Thunderstore ASAP.
