### ISSUE TITLE
Cannot modify accessories with PlayerOptimizationsEnabled set to true

### ISSUE THREAD

**Issue by g5bb** [tma02/calico#8]
Tested in a Calico enabled only environment in a solo lobby. When PlayerOptimizationsEnabled is set to true, you are unable to modify your own accessories, whatever you joined with, you are stuck with. 

- This only applies to accessories. 
- Hats, shirts, etc. function properly

**Comment by tma02** [comment]
Thanks! This is now fixed in 0.3.4.
